#!/bin/bash

# =================================================================
# EasyPharma Enterprise Configuration Script (2026 LTS Edition)
# Targets: Angular 21, NestJS 11, Prisma 7, Nx, pnpm
# =================================================================

echo "🚀 Initializing Enterprise Brain for EasyPharma..."

# 1. Create Directory Structure
echo "📁 Creating configuration folders..."
mkdir -p .agent/rules .agent/skills
mkdir -p .github/ISSUE_TEMPLATE
mkdir -p .github/workflows
mkdir -p .husky

# 2. .agent Configuration (The AI's "Standard Operating Procedures")
echo "🤖 Writing AI Agent Rules..."

# Global Project Rules
cat <<EOT > .agent/rules/global.md
# EasyPharma Global Rules
- **LTS Strictness**: Strictly use Angular 21.x and NestJS 11.x (Express). No experimental versions.
- **Architecture**: Nx Monorepo with Domain-Driven Design (DDD). 
- **ORM**: Prisma 7 (Schema-first).
- **Testing**: Use Vitest for Unit/Integration and Playwright for E2E. Minimum 80% coverage.
- **Documentation**: Swagger (API) and Compodoc (Frontend) must be autogenerated.
- **Workflow**: Commit small, atomic changes frequently to the main branch using Conventional Commits.
- **Autonomy**: Agent is authorized to run 'pnpm install', 'nx g', and 'prisma' commands.
EOT

# Frontend Specifics
cat <<EOT > .agent/rules/angular-21.md
# Angular 21 LTS Rules
- **Reactivity**: Use Signals for local state; NgRx Signal Store for global/shared state.
- **Zoneless**: All components must be zoneless (Angular 21 default).
- **Control Flow**: Use @if, @for, and @defer syntax only. No *ngIf or *ngFor.
- **Components**: 100% Standalone Components. No NgModules.
- **Documentation**: Use JSDoc comments for Compodoc auto-generation.
EOT

# Backend Specifics
cat <<EOT > .agent/rules/nestjs-11.md
# NestJS 11 LTS Rules
- **Adapter**: Express (Standard LTS).
- **Auto-Docs**: Ensure 'compilerOptions.plugins' in nest-cli.json includes '@nestjs/swagger/plugin'.
- **Validation**: Use Zod with 'nestjs-zod' for DTOs and runtime validation.
- **Architecture**: Controller -> Service -> Prisma Repository pattern.
EOT

# Security & RBAC
cat <<EOT > .agent/rules/security.md
# Pharmacy Security Rules
- **Auth**: Implement OIDC/JWT. All endpoints are protected by default.
- **RBAC**: Use @Roles('Admin', 'Pharmacist') decorators for NestJS and Functional Guards for Angular.
- **PII**: Mask Patient Identifiable Information in API responses using DTOs.
- **Audit**: Every inventory or prescription change must log the actor's ID.
EOT

# 3. .agent Skills (Teaching the AI "How" to act)
cat <<EOT > .agent/skills/git-autopilot.md
# Skill: Git Autopilot
- Task: Automatic version control.
- Action: After completing a sub-task (e.g., adding a service method, creating a DTO), stage changes and commit.
- Format: Conventional Commits (feat:, fix:, docs:, chore:).
- Context: Always reference the GitHub Issue number (e.g., feat(api): add drug search #12).
EOT

# 4. .github Configuration (Automation & Jira-lite)
echo "🐙 Setting up GitHub Workflows & Templates..."

cat <<EOT > .github/ISSUE_TEMPLATE/feature.md
---
name: "🚀 Feature Ticket"
about: Define a professional Pharmacy module.
title: "[FEAT]: "
labels: feature, enhancement
---
### 📖 User Story
As a **Pharmacist**, I want to **[action]** so that **[benefit]**.

### 🛠️ Technical Tasks
- [ ] NestJS 11 Service + Controller logic.
- [ ] Angular 21 Signal-based UI.
- [ ] Prisma Schema Update + Migration.
- [ ] Vitest unit tests (80% coverage).

### ✅ Definition of Done
- [ ] Swagger API docs updated.
- [ ] Build passes in CI.
EOT

cat <<EOT > .github/workflows/ci-docs.yml
name: MNC Compliance & Docs
on: [push]
jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm install
      - name: Verify Builds & Quality
        run: |
          pnpm nx affected:build
          pnpm nx affected:test
          pnpm run docs:gen
EOT

# 5. .husky Configuration (The Quality Gate)
echo "🐶 Initializing Husky..."
pnpm dlx husky init

cat <<EOT > .husky/pre-commit
#!/bin/sh
. "\$(dirname "\$0")/_/husky.sh"

echo "🧪 Running Quality Gate (Lint & Test)..."
pnpm nx affected:lint --uncommitted
pnpm nx affected:test --uncommitted
EOT

# 6. .nx / nx.json Configuration
echo "⚙️ Optimizing Nx for Enterprise Caching..."

cat <<EOT > nx.json
{
  "\$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": { "cache": true, "dependsOn": ["^build"], "inputs": ["production", "^production"] },
    "test": { "cache": true, "inputs": ["default", "^default", "{workspaceRoot}/vitest.config.ts"] },
    "lint": { "cache": true }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": ["default", "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)", "!{projectRoot}/tsconfig.spec.json", "!{projectRoot}/.eslintrc.json", "!{projectRoot}/vitest.config.ts"],
    "sharedGlobals": []
  },
  "plugins": ["@nx/angular", "@nx/nest"],
  "generators": {
    "@nx/angular:library": { "tags": ["scope:client", "type:feature"] },
    "@nx/nest:library": { "tags": ["scope:api", "type:feature"] }
  }
}
EOT

# 7. Quality Standards (SonarQube)
cat <<EOT > sonar-project.properties
sonar.projectKey=EasyPharma
sonar.projectName=EasyPharma
sonar.sources=apps,libs
sonar.exclusions=**/*.spec.ts, **/node_modules/**, **/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
EOT

chmod +x .husky/pre-commit
echo "✅ Configuration Sync Complete! EasyPharma is now ready for autonomous AI development."